### ISSUE TITLE
Verbesserungsvorschläge

### ISSUE THREAD

**Issue by Vernichtikus** [ccjj/rohaldors_dojo#1]
1. Eingabe der Schadenspunkte deutlicher machen
2. INI-Basis festlegen (bei gleicher INI wichtig)
3. Eventuell die Möglichkeit die Urpsrungswerte wiederherzustellen? Falls ein Blitz dich find wieder vorbei ist. Weiß nicht, wird wohl viel Arbeit sein bei vergleichsweise geringem Nutzen?
4. Möglichkeit TP (RS wird dann durch Programm abgezogen) oder SP (z.B. Fulminictus) zu verteilen

Hatten wir noch was?

**Comment by Vernichtikus** [comment]
1. Möglichkeit Gegner/Helden anzulegen und diese schnell zu laden.

**Comment by ccjj** [comment]
Alles außer 3. implementiert. Bin mir nicht sicher, wie man das darstellen soll (Rechtsklick auf eine Zeile, oder mit einer Checkbox, oder..). Als workaround geht erstmal, einzelne Personen in eine Personenliste zu speichern und ggfs. wieder zu laden.
